drop table if exists pictures;

CREATE TABLE pictures (
  id INTEGER  GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  url VARCHAR(80),
  favorited  INTEGER,
  breed  VARCHAR(80),
  name  VARCHAR(80)
);